#!/bin/bash
#PBS -l nodes=1:ppn=4

GENOME="mm9"
AVG=0
SCOREDIR="/home/pundhir/project/genome_annotations/phastCons46way/vertebrate"

#### usage ####
usage() {
	echo Program: "bed2conservation (compute phastcons or phyloP conservation score corresponding to input BED file)"
	echo Author: BRIC, University of Copenhagen, Denmark
	echo Version: 1.0
	echo Contact: pundhir@binf.ku.dk
	echo "Usage: bed2conservation -i <file> -o <dir> -s <dir>"
	echo "Options:"
	echo " -i <file>   [input file containing genomic coordinate in BED format (can be stdin)]"
    echo "             [format: chr start end unique_id class]"
    echo "             [NOTE: fourth column (name) should be unique]"
    echo " -o <dir>    [output directory]"
    echo " -s <dir>    [directory containing conservation score files]"
    echo "             [default: /home/pundhir/project/genome_annotations/phastCons46way/vertebrate]"
    echo "             [MORE INFO: https://www.biostars.org/p/129981/]"
    echo "             [MORE INFO: https://www.biostars.org/p/86847/]"
    echo "[OPTIONS]"
    echo " -g <string> [genome (default: mm9)]"
    echo " -y          [compute phyloP scores instead]"
	echo " -h          [help]"
	echo
	exit 0
}

#### parse options ####
while getopts i:o:s:g:yh ARG; do
	case "$ARG" in
		i) INPUTBEDFILE=$OPTARG;;
        o) OUTDIR=$OPTARG;;
        s) SCOREDIR=$OPTARG;;
        g) GENOME=$OPTARG;;
        y) PHYLOP=1;;
		h) HELP=1;;
	esac
done

## usage, if necessary file and directories are given/exist
if [ -z "$INPUTBEDFILE" -o -z "$OUTDIR" -o ! -d "$SCOREDIR" -o "$HELP" ]; then
	usage
fi

## create output directory, if it does not exist
if [ ! -d "$OUTDIR" ]; then
    mkdir -p $OUTDIR
fi

## populating files based on input genome
if [ "$GENOME" == "mm9" ]; then
    GENOME_FILE="/home/pundhir/project/genome_annotations/mouse.mm9.genome"
elif [ "$GENOME" == "hg19" ]; then
    GENOME_FILE="/home/pundhir/project/genome_annotations/human.hg19.genome"
else
    echo "Presently the program only support analysis for mm9 or hg19"
    echo
    usage
fi

## create temporary BED file if input is from stdin
if [ "$INPUTBEDFILE" == "stdin" ]; then
    TMP=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    while read LINE; do
        echo ${LINE}
    done | perl -ane '$line=""; foreach(@F) { $line.="$_\t"; } $line=~s/\t$//g; print "$line\n";' | sort -k 1,1 -k 2n,2 -k 3n,3 > $TMP
    INPUTBEDFILE=$TMP
fi

if [ ! -z "$PHYLOP" ]; then
    awk '{ regionChromosome = $1; regionStart = $2; regionStop = $3; regionID = $4; ID = $5; baseIdx = 0; for (baseStart = regionStart; baseStart < regionStop; baseStart++) { baseStop = baseStart + 1; print regionChromosome"\t"baseStart"\t"baseStop"\t"regionID"-"baseIdx"\t"ID; baseIdx++; } }' $INPUTBEDFILE > $OUTDIR/INPUTFILE_PER_BASE.BED

    ## compute phylop conservation scores for input BED file
    for i in `seq 1 22` X Y M;
    do
        phyloPFn="$SCOREDIR/chr${i}.phyloP46way.wigFix.bed"
        #echo "$phyloPFn"
        if [ $(ls $phyloPFn | wc -l) -eq 1 ]; then
            echo "mapping signal for chromosome chr${i}...";
            bedmap --echo --echo-map-score --delim '\t' $OUTDIR/INPUTFILE_PER_BASE.BED ${phyloPFn} > $OUTDIR/regions_with_perBase_phyloP.${i}.bed
        fi
    done
else
    ## compute phastcons conservation scores for input BED file
    for i in `seq 1 22` X Y M;
    do
        phastConFn="$SCOREDIR/chr${i}.phastCons*.wigFix.starch";
        #echo "$phastConFn"
        if [ $(ls $phastConFn | wc -l) -eq 1 ]; then
            echo "mapping signal for chromosome chr${i}...";
            bedmap --echo --mean --chrom chr${i} --delim '\t' $INPUTBEDFILE ${phastConFn} > $OUTDIR/regions_with_avg_phastcons.${i}.bed &
        fi
    done

    wait

    ## make final output file
    echo -e "make final output file.. "
    NCOL=$(cat $OUTDIR/regions_with_avg_phastcons.*.bed | head -n 1 | perl -ane 'print scalar(@F);')

    join -j 4 -o 1.1 1.2 1.3 1.4 1.5 2.$NCOL <(sort -k 4,4 $INPUTBEDFILE) <(cat $OUTDIR/regions_with_avg_phastcons.*.bed | sort -k 4,4) | perl -ane '$des=(); foreach(@F) { chomp($_); $des.="$_\t"; } $des=~s/\t$//g; print "$des\n";' > $OUTDIR/ALL.PHASTCONS
fi

## remove temporary file, if exists
if [ ! -z "$TMP" ]; then
    rm $TMP
fi
echo "done"

exit
