#!/bin/sh

# multijoin - join multiple files

join_rec() {
    if [ $# -eq 1 ]; then
        join -j 1 - "$1"
    else
        f=$1; shift
    join -j 1 - "$f" | join_rec "$@"
    fi
}

if [ $# -le 2 ]; then
    join -j 1 "$@"
else
    f1=$1; f2=$2; shift 2
    join -j 1 "$f1" "$f2" | join_rec "$@"
fi
